# Generated by Django 4.2.7 on 2023-11-16 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('ErrorID', models.AutoField(primary_key=True, serialize=False)),
                ('ErrorCode', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=250)),
                ('DateReceived', models.DateField()),
                ('ErrorLevel', models.CharField(choices=[('Критична', 'критична'), ('Важлива', 'важлива'), ('Незначна', 'незначна')], max_length=9)),
                ('FunctionalityCategory', models.CharField(choices=[('Інтерфейс', 'інтерфейс'), ('Дані', 'дані'), ('Розрахунковий алгоритм', 'розрахунковий алгоритм'), ('Інше', 'інше'), ('Невідома категорія', 'невідома категорія')], max_length=30)),
                ('Source', models.CharField(choices=[('Користувач', 'користувач'), ('Тестувальник', 'тестувальник')], max_length=20)),
            ],
            options={
                'verbose_name': 'Помилка',
                'verbose_name_plural': 'Помилки',
            },
        ),
        migrations.CreateModel(
            name='Programmers',
            fields=[
                ('ProgrammerID', models.AutoField(primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Програміст',
                'verbose_name_plural': 'Програмісти',
            },
        ),
        migrations.CreateModel(
            name='BugFixes',
            fields=[
                ('FixID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('FixDurationDay', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('WorkCostPerDay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ErrorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisplayCompany.errors')),
                ('ProgrammerCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisplayCompany.programmers')),
            ],
            options={
                'verbose_name': 'Виправленна помилка',
                'verbose_name_plural': 'Виправленні помилки',
            },
        ),
    ]
